### ISSUE TITLE
Download Link is Infinitely Redirecting

### ISSUE THREAD

**Issue by mklaber** [brutaldev/StrongNameSigner#12]
If ya' click *Download Installer* in `README.md`, you get an infinite redirect error. 

Example: [click here](http://www.brutaldev.com/file.axd?file=StrongNameSigner_Setup.exe) (if this link works, it's probably fixed)

Tried with Safari and Chrome.

**Comment by brutaldev** [comment]
All fixed up, that was a very old link and the URL re-write config for it is going to the completely wrong place. Fixed the re-write so your link works and changed the readme to the point to the new official link: http://brutaldev.com/download/StrongNameSigner_Setup.exe
