### ISSUE TITLE
Add a verbosity switch

### ISSUE THREAD

**Issue by mklaber** [brutaldev/StrongNameSigner#15]
Now that I've actually added this to my build process I'm faced with the incredibly verbose output it produces. While a "silent" mode would be nice, I probably wouldn't want it that quiet. It'd be great if it'd just print the assemblies that are fixed or signed. (e.g., don't print assemblies that have a `Nothing to fix...` result)

**Comment by brutaldev** [comment]
`LogLevel` parameter provided in [v1.4.6](https://github.com/brutaldev/StrongNameSigner/releases/tag/v1.4.6).

In your case, you would want to use the `Changes` level to only output any changes made (includes signing, reference corrections and IVT removals). Simply add `-l Changes` to your command-line arguments.

Certain log messages have been changed to ensure you are always aware of the file name being operated on.

**Comment by mklaber** [comment]
Awesome, as always.
