### ISSUE TITLE
Signed DLL that I can't reference anymore.

### ISSUE THREAD

**Issue by dretax** [brutaldev/StrongNameSigner#18]
Hello @brutaldev 

If I sign a dll, I can't reference It in my visual studio anymore. What's the problem? 

https://db.tt/LEmyvmWO

**Comment by brutaldev** [comment]
Hi @dretax 

Other assemblies that reference `UnityEngine` need to have their references fixed. When you sign `UnityEngine`, any assemblies that reference it will still reference the unsigned version unless you include them in the process to have their references "fixed" to point to the newly signed version.

Refer to the docs on how to deal with dependencies here: https://github.com/brutaldev/StrongNameSigner#dealing-with-dependencies

**Comment by dretax** [comment]
Cheers
