### ISSUE TITLE
Assembly reference not rewritten in XAML/BAML

### ISSUE THREAD

**Issue by JVimes** [brutaldev/StrongNameSigner#31]
I think I found an assembly reference that's not being rewritten by StrongNameSigner, and I may know where it is.

Repro steps:

1. Create a new "WPF Custom Control Library" project (not to be confused with "WPF User Control Library").
1. Build it.
1. Close the solution.
1. Create a new "WPF Application" project.
1. Configure the project for strong name signing (project settings > signing > etc.)
1. Add a project reference to the custom control library DLL, built above.
1. Add the Strong Name Signer nuget package to the project.
1. In MainWindow.xaml, replace the grid tag with this (the `xmlns` value assumes the above DLL and it's .NET namespace are `WpfCustomControlLibrary1`, so doctor it if necessary):
    ```
    <Grid xmlns:mylib="clr-namespace:WpfCustomControlLibrary1;assembly=WpfCustomControlLibrary1">
        <mylib:CustomControl1/>
    </Grid>
    ```
1. Build and run.

**Expected:** The application runs.
**Actual:** It throws an exception, "FileLoadException: Could not load file or assembly 'WpfCustomControlLibrary1, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)".

**I *may* know where the un-rewritten reference is.** I think it's an assembly self-reference in WpfCustomControlLibrary1.dll. That DLL contains a "generic.baml" resource (compiled from themes\generic.xaml in the project), and when I view it with dnSpy, there is a reference to the baml's own DLL, but with a null PublicKeyToken. I had to enable dnSpy's option: "View > Options > BAML decompiler > Disassemble BAML" to see the PublicKeyToken.

![image](https://cloud.githubusercontent.com/assets/6148201/23002830/174b567a-f3aa-11e6-87b2-818d25f2b05e.png)

**Edit:** Looks like normal references (across assemblies) also aren't rewritten in XAML/BAML. Guessing XAML isn't yet supported.

**Comment by pp111** [comment]
Hello, I am having the same problem. Did you find a solution for this?

**Comment by brutaldev** [comment]
Not yet, no time for this project at the moment.

**Comment by C1rdec** [comment]
Any news on this issue? 
Here is a simple repo: https://github.com/C1rdec/MaterialDesignStrongName

**Comment by brutaldev** [comment]
This works now when using v3.0.56-beta: https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/3.0.6-beta

**Comment by brutaldev** [comment]
Official release: https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/3.1.0
