### ISSUE TITLE
Incompattible with PackageReference

### ISSUE THREAD

**Issue by GieltjE** [brutaldev/StrongNameSigner#33]
When installing via nuget with the new PackageReference it isn't properly installed (it appears to have an incorrect file structure).

**Comment by brutaldev** [comment]
I actually have no idea what you're talking about...

**Comment by arledesma** [comment]
@brutaldev I think that @GieltjE is asking for [VS2017 PackageReference support](http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html).

**Comment by brutaldev** [comment]
Right, of course. I'll see if I can get around to this over the weekend.

**Comment by brutaldev** [comment]
Struggling to find time to look into this, if anyone wants to take a stab at figuring it out, I would welcome a pull request. In the meantime, just execute the console application as part of your build process which will work regardless of project format, NuGet version etc. Examples [in the build process section](https://github.com/brutaldev/StrongNameSigner#build-process).

**Comment by GieltjE** [comment]
Simply renaming the "build" folder to "lib" seems to solve the problem (remove the "obj" and "bin" folders before the first build). That would leave out any targeted building but for now would do the trick.

**Comment by brutaldev** [comment]
So in the NuGet package, should the `build` folder be `lib` instead? It used to be `tools` in v1.x and changed to `build`  in 2.x. I think it was a convention for build scripts since the target file was introduced in 2.0.

**Comment by GieltjE** [comment]
I think so, looking at existing packages (haven't read the documentation) the directory structure is
$userdir\.nuget\$packagename\$version\lib\$target (e.g. C:\Users\Administrator\.nuget\packages\mailkit\1.16.1\lib\net451, C:\Users\Administrator\.nuget\packages\mailkit\1.16.1\lib\MonoAndroid10, C:\Users\Administrator\.nuget\packages\mailkit\1.16.1\lib\Xamarin.iOS10).
But with the files in just \lib without a target it appears to work just fine.

This seems to be supported by https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package

**Comment by brutaldev** [comment]
I'll have to take a look at this change carefully, there must be a reason I used `build`. I'll try check it out over the weekend when I have a bit more time to spend on this.

**Comment by MichelZ** [comment]
Was there any progress on this?
Thanks

**Comment by Galad** [comment]
Hello @brutaldev 
Were you able to make any progress on this issue ?

Thanks

**Comment by brutaldev** [comment]
@Galad Nope, I simply haven't had the time to look into this, was hoping someone would be able to make a pull request for it.

**Comment by brutaldev** [comment]
Version [2.4.0](https://github.com/brutaldev/StrongNameSigner/releases/tag/2.4.0)  seems to work pretty well as a project reference now, path remains as "build" which will automatically identify the target file and use it as a build tool.
