### ISSUE TITLE
Caching problem

### ISSUE THREAD

**Issue by GieltjE** [brutaldev/StrongNameSigner#34]
When getting the AssemblyInfo for a file the result is somehow cached.

Reproduce, start with a signed assembly, run the code below, replace with unsigned assembly run code again (without closing the application):
                    AssemblyInfo assemblyInfo = SigningHelper.GetAssemblyInfo(file);
                    if (assemblyInfo.IsSigned) { MessageBox.Show("signed"); }
                    else {  SigningHelper.SignAssembly(....); }

**Comment by brutaldev** [comment]
The assembly details are indeed cached, but it should really be cleared if you run the process from the beginning again. Will make this update and release a new version over the weekend.

**Comment by GieltjE** [comment]
The problem is that our process remains running for weeks at a time (custom build & release tool).

Good to hear there is a patch inbound 👍

**Comment by brutaldev** [comment]
This should be fixed up in release [2.1.1](https://github.com/brutaldev/StrongNameSigner/releases/tag/v2.1.1).

The file is hash checked first to ensure the cached version is still pointing to the same file.
