### ISSUE TITLE
2.1.1 SignAssembly Keeps files locked

### ISSUE THREAD

**Issue by GieltjE** [brutaldev/StrongNameSigner#35]
2.1.0 works great, but in 2.1.1 after calling SignAssembly(....) the file remains locked untill the application is closed.

E.g. we use a temporary directory to sign files, signing the same dll for multiple DotNet versions causes problems as we cannot delete them after signing.

**Comment by brutaldev** [comment]
Fixed up in release [2.1.2](https://github.com/brutaldev/StrongNameSigner/releases/tag/v2.1.2). Updated to a new version of Mono.Cecil which seems to hold file locks so this release just reverts back to the trusty stable release.
