### ISSUE TITLE
New Variable to locate StrongNameSigner

### ISSUE THREAD

**Issue by tomap** [brutaldev/StrongNameSigner#36]
Hi,

Could you add a new variable here to locate StrongNameSigner?
Here: 
https://github.com/brutaldev/StrongNameSigner/blob/master/src/Brutal.Dev.StrongNameSigner/StrongNameSigner.targets#L20

You could declare
`<StrongNameSignerDirectory>$(MSBuildThisFileDirectory)</StrongNameSignerDirectory>`

So that from pre / post build step, we can use this variable to find Brutal.Dev.StrongNameSigner console and not hardcode the path containing the version (curerntly Brutal.Dev.StrongNameSigner.2.1.2)

Thank you

**Comment by brutaldev** [comment]
Hey @tomap 
I wouldn't even know where to start or how to test that. My MSBuild skills are sketchy at best so if you could submit a PR with an example of how to make use of it I'll happily accept and release another build.

**Comment by tomap** [comment]
Done, see https://github.com/brutaldev/StrongNameSigner/pull/37

**Comment by brutaldev** [comment]
Awesome, thanks! Just did some reading and that's pretty useful, it is a pain updating the version each time for me as well so I'll make use this... Will merge and release in a couple of hours when I get back on my dev machine.

**Comment by brutaldev** [comment]
Released the changes: https://github.com/brutaldev/StrongNameSigner/releases/tag/v2.1.3
