### ISSUE TITLE
Build Process Integration via Nuget Pacakge does not work

### ISSUE THREAD

**Issue by rufio620** [brutaldev/StrongNameSigner#39]
I installed the nuget package and attempted to build. My build immediately fails and all the assemblies in the project fail to resolve in my project.  I'm not sure if I am doing something wrong or if something is broken. Any help is much appreciated.

![image](https://cloud.githubusercontent.com/assets/1992395/26559426/87cff1f2-447d-11e7-8d39-707db1fb84ee.png)

**Comment by brutaldev** [comment]
Duplicate of issue #27.
