### ISSUE TITLE
Debug directory removed from PE header

### ISSUE THREAD

**Issue by Sam13** [brutaldev/StrongNameSigner#44]
By comparing the PE header of an existing unsigned assembly and the same assembly signed with StrongNameSigner, I found out that the "Debug directory" is stripped out from the PE header.

Without information in the header that it's e.g. impossible to generate a PDB with JetBrains dotPeek (https://youtrack.jetbrains.com/issue/DOTP-6889)

I'm using version 2.1.4

**Comment by brutaldev** [comment]
@Sam13 I've tested this myself and the directory is not stripped at all. Do you have an assembly with corresponding PDB that this happens with? I used tools like [PE Editor](https://github.com/petoolse/petools) to verify the header.

**Comment by Sam13** [comment]
@brutaldev I'm afraid, I cannot provide any test data. Since you tested again I would consider this fixed...
