### ISSUE TITLE
Creating Post Build Scripts

### ISSUE THREAD

**Issue by RealDotNetDave** [brutaldev/StrongNameSigner#45]
It would be nice if the Strong-Name Signer app could create the post build scripts needed in Visual Studio for creating NuGet package.

David McCarter

**Comment by brutaldev** [comment]
Reading this again and I'm actually lost as to what is being asked here?
Going to wait a couple days for a better explanation of this request and close it if there is no response.

**Comment by RealDotNetDave** [comment]
That was so long ago, I don't remember. Go ahead and close.

**Comment by brutaldev** [comment]
No problem, tried to think of a use case for this but also stumped. Closing because there is not enough information.
