### ISSUE TITLE
Not work for Auth0.Core 5.10.0 package

### ISSUE THREAD

**Issue by chessar** [brutaldev/StrongNameSigner#49]
Could not load file or assembly 'Auth0.Core, Version=5.10.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).

For more info see [https://github.com/auth0/auth0.net/issues/207](https://github.com/auth0/auth0.net/issues/207)

**Comment by brutaldev** [comment]
Besides the fact they have a signed version coming up. I write a quick test app using the three assemblies you mentioned and made a call to `GetTokenAsync` after signing and it works well.
If you cannot provide a sample application that fails the way you describe, there is not much I can do to help. I used NuGet package version [2.4.0](https://github.com/brutaldev/StrongNameSigner/releases/tag/2.4.0).
