### ISSUE TITLE
Any reason for clearing source linking information?

### ISSUE THREAD

**Issue by paulomorgado** [brutaldev/StrongNameSigner#50]
I'm trying to add source linking to a lib but the StrongNameSigner seems to be erasing the source linking information.

**Comment by paulomorgado** [comment]
Looks like it was a [problem](https://github.com/jbevain/cecil/issues/412), but has been [solved](https://github.com/jbevain/cecil/pull/432).

**Comment by brutaldev** [comment]
This may have been fixed up now after adding the latest version of Mono.Cecil in [v2.4](https://github.com/brutaldev/StrongNameSigner/releases/tag/2.4.0)
