### ISSUE TITLE
StrongNameSignerTarget executes too long

### ISSUE THREAD

**Issue by radevop** [brutaldev/StrongNameSigner#51]
Hello, 

I want to use your tool to automatically sign two dll's from external nuget packages that I used in my solution. Problem is that your task checks all dll inside nuget download folder (in my case it is C:\Users\USERNAME\.nuget\packages which contain 26 folders/packages) so execution time of single build takes too much time, more than 8 minutes. Is it an option to give the mask of dll's/packages that will specify for dll's file names that tool really needs to be signed?

**Comment by brutaldev** [comment]
If you need to filter just the assemblies you want to sign, you can provide patterns with the `-in` parameter when using it as part of the build process. Using the build target at the moment does not allow for patterns (you're welcome to add that functionality if you want) so you can use the command-line app to run BeforeBuild. The documentation highlights how to do this already, a pattern example can be found under [Dealing With Dependencies](https://github.com/brutaldev/StrongNameSigner#dealing-with-dependencies).
