### ISSUE TITLE
Unknown blob format

### ISSUE THREAD

**Issue by davidkdb** [brutaldev/StrongNameSigner#54]
I get this message when trying to sign an assembly:

Strong-name signing ...nuget\packages\shopifysharp\4.21.7\lib\net45\ShopifySharp.dll...
Error strong-name signing ...nuget\packages\shopifysharp\4.21.7\lib\net45\ShopifySharp.dll: Unknown blob format.

**Comment by brutaldev** [comment]
Just tested successfully using version 2.4, are you using the latest version?

**Comment by davidkdb** [comment]
Yes, you're right. It worked when I did not use my own certificate.
