### ISSUE TITLE
Disable signing packages

### ISSUE THREAD

**Issue by fpavlic** [brutaldev/StrongNameSigner#56]
Hi,

I'm using Brutal.Dev.StrongNameSigner Nuget package, had used "Before Build" process to sign un-signed packages. Those packages will not be updated that frequently so I would like to disable signing & checking.

Is there option to do that?

**Comment by brutaldev** [comment]
Currently no option for that, suppose this could be an environment variable that you set otherwise you will need to change your project settings all the time. Will think about it and put something in the next release.

**Comment by fpavlic** [comment]
@brutaldev either environment variable or setting in e.g. global.asax on application start. Could be helpful because I noticed increase in build time, even if those packages are already signed.

**Comment by brutaldev** [comment]
Added check for environment variable `SNS_DISABLE_CONSOLE_SIGNING` in version [2.6.0](https://github.com/brutaldev/StrongNameSigner/releases/tag/2.6.0). Use the value `true` to skip signing (a warning will also appear in your log).
