### ISSUE TITLE
Satellite assemblies located with other files

### ISSUE THREAD

**Issue by mklemarczyk** [brutaldev/StrongNameSigner#65]
Hello, I got an issue when using console for signing files.
The output directory was in flat structure. I needed to recreate the file structure of the original release.
The satellite assemblies usually have specific structure for example for resource assemblies.

I created Pull Request #64 to address this issue, it introduces new option that allows preserve file structure in output directory.

More info about satellite assemblies can be found:
https://docs.microsoft.com/en-us/dotnet/core/extensions/create-satellite-assemblies

**Comment by brutaldev** [comment]
PR accepted.
