### ISSUE TITLE
In 2.9.0 release, usage of parameter -a to sign a single assembly is broken 

### ISSUE THREAD

**Issue by samarunraj** [brutaldev/StrongNameSigner#66]
https://github.com/brutaldev/StrongNameSigner/blob/330a4ce1596333a3c2f0f824e0e58728651f8a53/src/Brutal.Dev.StrongNameSigner.Console/Program.cs#L152

The above line assumes InputDirectory is valid when "-a" option is used. `StrongNameSigner.Console -a MyUnsignedAssembly.dll -k PersonalKey.snk`

**Comment by brutaldev** [comment]
Thanks, fixed in 2.9.1: https://github.com/brutaldev/StrongNameSigner/releases/tag/v2.9.1
