### ISSUE TITLE
Select keyfile makes window very small

### ISSUE THREAD

**Issue by wonea** [brutaldev/StrongNameSigner#68]
Select a keyfile, and the program window shrinks on 4k.
![image](https://user-images.githubusercontent.com/557192/148992634-3a44694e-b76d-4aa3-99c7-69ed41036cb8.png)

**Comment by brutaldev** [comment]
So this is the problem: https://stackoverflow.com/questions/42975285/commonopenfiledialog-cause-windows-form-to-shrink

Will add the DPI support and release a new version.

**Comment by brutaldev** [comment]
Fixed up in [v3.1.1](https://github.com/brutaldev/StrongNameSigner/releases/tag/v3.1.1)

**Comment by wonea** [comment]
Fantastic that's brilliant. Any chance of a dark theme?

**Comment by brutaldev** [comment]
@wonea Hehe, now you're pushing your luck :)
It's using good old Windows Forms so it's now that easy to style things differently. I'm also not much of a designer so I probably won't get it right...
