### ISSUE TITLE
It seems not working in sdk-style project with third-part packages

### ISSUE THREAD

**Issue by songjiefa** [brutaldev/StrongNameSigner#69]
I created a wpf project with sdk-style .net 4.8, then, I reference un strong name package and  strong name signer, when I build it, it shows "no assembly paths were  provided" and it works fine in ms-build project

**Comment by brutaldev** [comment]
@songjiefa please provide a sample project so we can reproduce the problem.

**Comment by songjiefa** [comment]
Here is my sample coede: https://github.com/songjiefa/TestStrongNameSinger

**Comment by brutaldev** [comment]
@songjiefa Apologies for the delay, I'm battling with COVID at the moment so my head hasn't been in code for a while...
The link you provided gets to a 404 page, any other way  you can get me a sample project to reproduce the problem with?

**Comment by brutaldev** [comment]
@songjiefa The automatic build task uses the reference list to determine which dependencies to sign. Your SDK project has package references but no project references so it does not find anything to sign. To overcome this you need to add a build target yourself: https://github.com/brutaldev/StrongNameSigner/blob/master/README.md#dealing-with-dependencies

In `SdkStyle-Failed.csproj` add the following pre-build target:
```
<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec ContinueOnError="false" 
          Command="&quot;$(StrongNameSignerDirectory)StrongNameSigner.Console.exe&quot; -in &quot;$(UserProfile)\.nuget\packages\ardalis.guardclauses&quot;" />
</Target>
```
