### ISSUE TITLE
Transitive dependencies from PackageReferences are not investigated/signed

### ISSUE THREAD

**Issue by DoctorVanGogh** [brutaldev/StrongNameSigner#73]
I've come across a tricky issue with StrongNameSigner.

If you have a nuget package referenced via `PackageReference` but that package is (mostly) a metapackage - meaning it has a lots of dependencies into *other* nuget packages - StrongNameSigner will only - if ever - sign the direct dependency.

If you have dependencies like
```
Project
  nuget -> Foo
    nuget -> Bar
    nuget -> Baz
  nuget -> StrongNameSigner
```
Only the direct assemblies from Foo will ever get looked at.

Here's an example project & program:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>foo.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Brutal.Dev.StrongNameSigner" Version="3.1.1" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
  </ItemGroup>

</Project>
```
```cs
using Nito.AsyncEx;
using System;
using System.Threading.Tasks;

namespace Demo {
    public class Program {
        public async static Task Main(string[] args) {
            Console.WriteLine("Waiting...");
            var al = new AsyncLazy<int>(Foo);

            Console.WriteLine(await al);
        }

        public async static Task<int> Foo() {
            await Task.Delay(2000);
            return 42;
        }
    }
}
```

SNS will not sign anything in this situation. 
And of course, the resulting assembly wont run :(

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Nito.AsyncEx.Coordination, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

*Should* this be supported by SNS?

**Comment by brutaldev** [comment]
This _should_ be supported and _should_ work because for each referenced assembly the entire dependency tree is traversed and all unsigned references will get signed and their references changed in the parent.

Thanks for the example code, will reproduce this and see if it can be fixed. I think your mention of "metepackage" might be the root cause because there is not direct reference to an assembly to start traversing from.

**Comment by nickrandolph** [comment]
@brutaldev doesn't the code exclude any references coming from nuget packages?
see https://github.com/brutaldev/StrongNameSigner/blob/c38d42ab8d1444504720a62736b310303236cd85/src/Brutal.Dev.StrongNameSigner/AutomaticBuildTask.cs#L73
