### ISSUE TITLE
Virus Detected on Chrome when downloading StrongNameSigner_Setup.exe

### ISSUE THREAD

**Issue by PeteSral** [brutaldev/StrongNameSigner#79]
Unable to download the setup.exe in Chrome:
![virus detected](https://user-images.githubusercontent.com/36866437/208159519-f818e80f-3629-43cf-98de-45b3a624bd2e.png)

**Comment by brutaldev** [comment]
That's nice. Use another browser then cause there are no viruses here. Maybe Chrome flags everything from GitHub cause they don't like Microsoft.

I also tried in Chrome just to double check and it had no issues with the same download from my official site: https://brutaldev.com/post/net-assembly-strong-name-signer
