### ISSUE TITLE
Fixing up references sometimes invalidates the assembly

### ISSUE THREAD

**Issue by Bringer128** [brutaldev/StrongNameSigner#8]
Hey there,

I have a scenario where I have 3 assemblies that need to be referenced by a strong-name signed project. One is a 3rd party library and 2 are created by me, but I don't want to make them strong-name signed.

* ThirdPartyLib.dll
* MyLib.dll (depends upon ThirdPartyLib.dll)
* MyLib2.dll (depends upon ThirdPartyLib and MyLib)
* MyProject.csproj (depends upon ThirdPartyLib.dll, MyLib and MyLib2)

What I've found is that in my case, MyLib2.dll is correctly compiled, but when loaded I get the error:

> Could not load file or assembly 'MyLib2' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

I've narrowed this error down to this line: https://github.com/brutaldev/StrongNameSigner/blob/59ea220c10fa04ebff3360fb737fbcb2f78de5b1/src/Brutal.Dev.StrongNameSigner/SigningHelper.cs#L249

If I set a breakpoint before this line and use "sn.exe -v MyLib2.dll" it responds saying MyLib2.dll is valid. If I then step over this line and check again with sn.exe it responds with the "String name signature could not be verified".

I then did a quick test by hardcoding this line to this:

    a.Write(assemblyPath, new WriterParameters { StrongNameKeyPair = GetStrongNameKeyPair("C:\\path\\to\\MyKeyPair.snk", null) });

And this causes the problem to disappear.

Unfortunately I haven't had time yet to create a simple failing test case but it looks to me to be a fairly simple change. I'll have a look tomorrow about coming up with a failing unit test and a pull request to fix it.

**Comment by brutaldev** [comment]
Thanks, I reviewed, merged your fixes and released a new version.
https://github.com/brutaldev/StrongNameSigner/releases/tag/1.4.3

Don't worry about the test case, I can't get this to happen either but the code change makes sense.
