### ISSUE TITLE
[Bug]: When the GUI comes across a "Unsupported PDB deleted bitset is not empty" it stops processing

### ISSUE THREAD

**Issue by Smurf-IV** [brutaldev/StrongNameSigner#86]
Open a directory and place all dll's / exe's into the list and click open

Expected: 
- Warnings to be displayed for non-loadable binaries (like CPP and fortran dll's)

Actual:
- Boom message with "Unsupported PDB deleted bitset is not empty" and then **no more** files are processed.

**Comment by brutaldev** [comment]
Cannot catch that specific exception but the UI was only looking at bad image formats so added generic exception handling blocks to avoid the process from stopping.
