### ISSUE TITLE
[Feature Request]: convert the "Unsupported PDB deleted bitset is not empty" Error to a warning, so that the commandline app does not report errors

### ISSUE THREAD

**Issue by Smurf-IV** [brutaldev/StrongNameSigner#87]
The above is generated for a C++ Dll that has `/clr` set

**Comment by brutaldev** [comment]
That exception was actually removed from Mono.Cecil so not sure what is throwing it: https://github.com/jbevain/cecil/commit/2c6892705c20294859da5bc36f9b82f60aa333c7

The exception is also internal so cannot be caught. Ultimately, it's still an error and the console will show an error, you shouldn't be trying to sign these types of files.

**Comment by Smurf-IV** [comment]
> The exception is also internal so cannot be caught. Ultimately, it's still an error and the console will show an error, you shouldn't be trying to sign these types of files.

@brutaldev 
When passing a command line of *.dll for a hundred files and this throws on 1 of them, then there needs to be an override
