### ISSUE TITLE
[Change Request]: Please change the column named `Signed` to be `StrongNamed`

### ISSUE THREAD

**Issue by Smurf-IV** [brutaldev/StrongNameSigner#90]
This is to allow also checking if the binary has been actually `signed` with a digital certificate, which is independent of the "String naming" operation with a certificate.

**Comment by brutaldev** [comment]
In the context of the application (strong-name signing) the column is not ambiguous since this has nothing to do with digital certificates or authenticode signing and it's referring to strong-name signing. Still changed it to "Strong-named" because of #91
