### ISSUE TITLE
[Feature Request]: Have a column called `DigCert` to show if this binary also has been digitally signed

### ISSUE THREAD

**Issue by Smurf-IV** [brutaldev/StrongNameSigner#91]
Perhaps this could also be a "Button" (if true:  to show/ test that the cert is valid)

**Comment by brutaldev** [comment]
No. The application is for strong-name signing not digital signing. Checking digital signatures is completely out of scope and not something I'll be adding, there are enough tools out there that do this already.

**Comment by Smurf-IV** [comment]
FYI; I Created a tool:
https://github.com/Smurf-IV/IsStrongOrSigned
