### ISSUE TITLE
Can not get it to work with .NET Standard 2.0 Project and Nuget Packages Scrypt.NET and CSVTextFieldParser

### ISSUE THREAD

**Issue by meneasysoft** [brutaldev/StrongNameSigner#95]
Thank you for your valuable work, in projects with .NET 4.8 the StrongNameSigner works very well and reliable.

But somehow I can not get it to work with a .NET Standard 2.0 Project and the Nuget Packages Scrypt.NET 1.3.0 and CsvTextFieldParser 1.2.2

You can find a demo project here to reproduce the issue:
https://github.com/meneasysoft/SigningNetStd20

I still get the following warnings:
Referenced assembly "Scrypt, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null" does not have a strong name
Referenced assembly "CsvTextFieldParser, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null" does not have a strong name

How do I fix this?
Do I have to put an extra reference to the DLL in to the project file?
All help is appreciated.

Thank you in advance!

**Comment by brutaldev** [comment]
Typically packages in the `.nuget` directory are ignored: https://github.com/brutaldev/StrongNameSigner/blob/master/src/Brutal.Dev.StrongNameSigner/AutomaticBuildTask.cs#L77

```
1>    Ignored 'C:\Users\X\.nuget\packages\csvtextfieldparser\1.2.2\lib\netstandard2.0\CsvTextFieldParser.dll' cached/framework NuGet package.
1>    Ignored 'C:\Users\X\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll' cached/framework NuGet package.
1>    Ignored 'C:\Users\X\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\mscorlib.dll' cached/framework NuGet package.
1>    Ignored 'C:\Users\X\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref\netstandard.dll' cached/framework NuGet package.
1>    Ignored 'C:\Users\X\.nuget\packages\scrypt.net\1.3.0\lib\netstandard1.4\Scrypt.dll' cached/framework NuGet package.
...
```

I can remove this line but who knows what kind of havoc that's going to cause... Perhaps @nickrandolph has some ideas on how to control this from the targets file?

**Comment by meneasysoft** [comment]
Hello @brutaldev ,

thank you very much for the quick response. That information helped a lot.
I simply now put a NuGet.config into my Solution with the following content to ensure that it is not taken from the users .nuget Directory:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<config>
		<add key="globalPackagesFolder" value=".\packages" />
	</config>
</configuration>`

See https://stackoverflow.com/questions/43687058/how-do-i-include-nuget-packages-in-my-solution-for-net-core-projects

No need to adjust anything then on your side. You can close this issue!
