### ISSUE TITLE
Determinism?

### ISSUE THREAD

**Issue by KirillOsenkov** [brutaldev/StrongNameSigner#99]
I think I'm seeing the public key token of the assemblies signed by StrongNameSigner differ across builds. 

Could you please point me to the source where the key pair is generated?

I'm wondering if we could make it deterministic, e.g. derive the public key token from the SHA hash of the assembly name.

Would be nice to have it deterministic and not change across builds (always same public key token for the same assembly) because this way you can add a binding redirect to the app.config and specify the public key token.

Thanks!

**Comment by brutaldev** [comment]
Hi @KirillOsenkov 

If you do not specify a key file to use, then [one is generated](https://github.com/brutaldev/StrongNameSigner/blob/fe3e5024abfc0cdc7339dec66cc22dd5994d8f73/src/Brutal.Dev.StrongNameSigner/SigningHelper.cs#L530) each time you run it.

If you are using the console application, use the `-k` argument with a path to your own key file.
If you are using the build task, then you can set the `$(StrongNameKeyFile)` variable for the [MSBuild target](https://github.com/brutaldev/StrongNameSigner/blob/fe3e5024abfc0cdc7339dec66cc22dd5994d8f73/src/Brutal.Dev.StrongNameSigner/StrongNameSigner.targets#L9).

To generate a strong name key file, follow the steps highlighted here: https://learn.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair
You can also use your own PFX file if you are signing your own assemblies that way.

**Comment by KirillOsenkov** [comment]
Thanks!
